name: Remote Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Npm Install
        run: npm i
      - name: configure ssh connection
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -t ed25519 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          eval "$(ssh-agent -a $SSH_AUTH_SOCK)"
          echo "${{ secrets.SSH_KEY }}" | ssh-add -
      - name: Deploy
        run: npm run deploy
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock